<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MiniDemo\MiniDemo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Canton.Ledger.Testing" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

</Project>
